pipeline {
    agent any

    environment {
       CURRENT_TIME=''
    }
    stages {
        stage('initialize') {
            steps {
                script {
                    // 현재 시간을 변수에 저장
                    env.CURRENT_TIME = new Date().getTime()
                }
            }
        }

        stage('checkout') {
            steps {
                git url: 'https://github.com/Epstein-Conbus/simple-node-js-react-npm-app.git', branch: 'master'
            }
        }
        stage('deploy') {
            steps {
                echo 'deploying the application...'
                sh 'npm install'
            }
        }
        stage('file edit') {
            steps {
                sh """
                    FILE_PATH="./src/App.js"
                    OLD_STRING="console.log([0-9]+)"
                    NEW_STRING="console.log(\${env.CURRENT_TIME})"

                    if [ -f "\$FILE_PATH" ]; then
                        sed -E "s|\$OLD_PATTERN|\$NEW_STRING|g" "\$FILE_PATH" > "\$FILE_PATH.tmp"
                        mv "\$FILE_PATH" "\$FILE_PATH.bak"
                        mv "\$FILE_PATH.tmp" "\$FILE_PATH"
                        echo "파일 수정 완료: \$FILE_PATH"
                    else
                        echo "파일을 찾을 수 없습니다: \$FILE_PATH"
                        exit 1
                    fi
                """
            }
        }
        stage('Commit Changes') {
            steps {
                script {
                    // 변경 사항 커밋
                    sh """
                        git add .
                        if git diff-index --quiet HEAD; then
                            echo "No changes detected"
                        else
                            git commit -m "Jenkins has merged this build"
                        fi
                    """
                }
            }
        }
        stage('Merge to Master') {
            steps {
                // 변경 사항을 main 브랜치에 머지
                sh """
                    git checkout master
                    git pull origin master
                    git merge --no-ff your-feature-branch
                    git push origin master
                """
            }
        }


    }
}